import localFont from "next/font/local";
import "./globals.css";

const montreal = localFont ({
  src: "./fonts/Montreal-Regular.ttf",
  variable: "--font-montreal",
  weight: "400",
});

const montrealBold = localFont ({
  src: "./fonts/Montreal-Bold.ttf",
  variable: "--font-montreal-bold",
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montreal.variable} ${montrealBold.variable} antialiased bg-[#f2f2f2]`}
      >        
        <Nav />
        <div className="pt-28">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
